name: CI/CD Pipeline #Name workflow

on:
  push:
    branches:
      - develop
      - release/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: ./deploy.sh
